### ISSUE TITLE
Can you customize CSS preprocessor used?

### ISSUE THREAD

**Issue by DCzajkowski** [zaknes/tailwind-preset#1]
Great job! My only concern is that you are currently using Less by default. Are you planning on implementing CLI options for Sass and pure CSS? If so, what is the ETA?

I think it should be also noted in the readme, that Less is the default currently.

**Comment by zaknesler** [comment]
I would not be opposed to adding them, per se. For now, I am more focused on the structure and the overall feel of the design more than the extensibility towards other preprocessors, considering that would require the updating of several files just to make a single change. So I will keep this in mind for a future release!

**Comment by zaknesler** [comment]
@DCzajkowski I looked into this, and because the `PresetCommand` class is already registered, and is extended via macro, you cannot add any other arguments or options to the command. Creating a new command is redundant, and adding a separate command for each preprocessor does not make much sense, either.

Do you have any ideas as to how it should be done? If not, I'm just going to hold off on this idea and leave it as Less. I guess it's also worth mentioning that no other preset has this option available.

**Comment by zaknesler** [comment]
I'm going to close this for now, as there isn't a great way to handle this, and would only complicate things in the future.
